apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ticketing

spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ticket-config
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
      - name: pg-data
        persistentVolumeClaim:
         claimName: pg-data
      - name: db-init
        configMap:
          name: db-init-scripts
          items:
            - key: init.sql
              path: init.sql