apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
  namespace: ticketing
spec:
  replicas: 3
  selector: 
   matchLabels: 
    app: frontend
  template: 
   metadata: 
    labels:
     app: frontend
   spec:
    containers: 
    - name: frontend
      image: sunseyy/ticketing-frontend:latest
      envFrom:
       - configMapRef:
          name: ticket-config
      ports:
      - containerPort: 80                                          