apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
  namespace: ticketing
data:
  # VARIABLES POUR POSTGRESQL (au démarrage du conteneur)
  POSTGRES_DB: "ticketing"      # OBLIGATOIRE : crée la base automatiquement
  POSTGRES_HOST: "postgres"     # (nom du service Kubernetes)
  POSTGRES_PORT: "5432"         

  # VARIABLES POUR (backend)
  DB_HOST: postgres   
  DB_NAME: ticketing  
  DB_PORT: "5432"
  NODE_ENV: production

  VITE_API_URL: "/api"  
  CORS_ORIGINS: "http://ticketing.local:32374"