apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  namespace: ticketing
data:
  init.sql:  |
     SET statement_timeout = 0;
     SET lock_timeout = 0;
     SET idle_in_transaction_session_timeout = 0;
     SET client_encoding = 'UTF8';
     SET standard_conforming_strings = on;

     SET search_path = public;
     SET check_function_bodies = false;
     SET xmloption = content;
     SET client_min_messages = warning;
     SET row_security = off;

     SET default_tablespace          = '';
     SET default_table_access_method = heap;

    
     CREATE TYPE user_role AS ENUM ('CLIENT', 'AGENT', 'ADMIN');
     CREATE TYPE ticket_status AS ENUM ('OPEN', 'IN_PROGRESS', 'WAITING_ON_CLIENT', 'RESOLVED', 'CLOSED');
     CREATE TYPE ticket_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');


     CREATE OR REPLACE FUNCTION update_modified_column()
     RETURNS TRIGGER AS $$
     BEGIN
         NEW.updated_at = NOW();
         RETURN NEW;
     END;
     $$ language 'plpgsql';


     CREATE TABLE public.societies (
         id SERIAL PRIMARY KEY,
         name character varying(255) NOT NULL,
         type character varying(50) NOT NULL,
         contact_email character varying(255),
         created_at timestamp without time zone DEFAULT now(),
         updated_at timestamp without time zone DEFAULT now(),

         deleted_at timestamp without time zone,
         CONSTRAINT societies_type_check CHECK (((type)::text = ANY ((ARRAY['client'::character varying, 'tech'::character varying])::text[])))
     );

     CREATE TABLE public.users (
         id SERIAL PRIMARY KEY,
         full_name character varying(255) NOT NULL,
         email character varying(255) UNIQUE NOT NULL,
         password_hash text NOT NULL,
         role user_role NOT NULL,
         society_id integer REFERENCES public.societies(id) ON DELETE SET NULL,
         created_at timestamp without time zone DEFAULT now(),
         updated_at timestamp without time zone DEFAULT now(),
         deleted_at timestamp without time zone
     );

     CREATE TABLE public.tickets (
         id SERIAL PRIMARY KEY,
         title text NOT NULL,
         description text NOT NULL,
         product character varying(100) NOT NULL,
         category character varying(100) NOT NULL,
         department character varying(100) NOT NULL,

         priority ticket_priority DEFAULT 'MEDIUM'::ticket_priority NOT NULL,
         urgency character varying(20),
         status ticket_status DEFAULT 'OPEN'::ticket_status NOT NULL,
         created_by integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
         society_id integer REFERENCES public.societies(id) ON DELETE SET NULL,
         assigned_agent_id integer REFERENCES public.users(id) ON DELETE SET NULL,
         created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
         updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
         deleted_at timestamp without time zone,
         CONSTRAINT tickets_urgency_check CHECK (((urgency)::text = ANY ((ARRAY['Low'::character varying, 'Medium'::character varying, 'High'::character varying])::text[])))
     );

     CREATE TABLE public.comments (
         id SERIAL PRIMARY KEY,
         ticket_id integer NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
         user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
         content text NOT NULL,
         created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
         updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
         deleted_at timestamp without time zone
     );

     CREATE TABLE public.attachments (
         id SERIAL PRIMARY KEY,
         ticket_id INTEGER REFERENCES public.tickets(id) ON DELETE CASCADE,
         comment_id INTEGER REFERENCES public.comments(id) ON DELETE CASCADE,
         uploaded_by INTEGER NOT NULL REFERENCES public.users(id),
         file_name TEXT NOT NULL,
         file_path TEXT NOT NULL,
         file_size INTEGER NOT NULL,
         content_type TEXT NOT NULL,
         created_at timestamp without time zone DEFAULT now(),
         deleted_at timestamp without time zone
     );


     CREATE TRIGGER update_societies_modtime BEFORE UPDATE ON public.societies FOR EACH ROW EXECUTE FUNCTION update_modified_column();
     CREATE TRIGGER update_users_modtime BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_modified_column();
     CREATE TRIGGER update_tickets_modtime BEFORE UPDATE ON public.tickets FOR EACH ROW EXECUTE FUNCTION update_modified_column();
     CREATE TRIGGER update_comments_modtime BEFORE UPDATE ON public.comments FOR EACH ROW EXECUTE FUNCTION update_modified_column();


     INSERT INTO public.societies (id, name, type, contact_email, created_at, updated_at) VALUES
     (3, 'ByteWorks', 'tech', 'hello@byteworks.com', '2026-02-13 12:48:05.577654', '2026-02-13 12:48:05.577654'),
     (5, 'Algérie Télécom', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073'),
     (6, 'Fortinet', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073'),
     (7, 'Ooredoo', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073'),
     (8, 'Natixis', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073'),
     (9, 'Ericsson', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073'),
     (10, 'Société Générale', 'client', NULL, '2026-02-14 16:27:11.905073', '2026-02-14 16:27:11.905073');

     INSERT INTO public.users (id, full_name, email, password_hash, role, society_id, created_at) VALUES
     (1, 'sara', 'sarab@gmail.com', '$2b$10$BHGoGG79ShH0lN/oUaNeVODvJOeLxlXDBoy8TQIHvgA/CFauRhc9m', 'AGENT', NULL, '2026-02-14 19:16:32.908648'),
     (5, 'sarah', 'sarawb@gmail.com', '$2b$10$o5uJAm03bERetDtzxor1YuEV.B2oRcYW5VWikEqRB0VE7qUTZPwmy', 'CLIENT', 6, '2026-02-14 18:25:03.354848'),
     (6, 'System Admin', 'admin@tnd.dz', '$2b$10$XCVqyB0OKoK6F.CDT8COEuQs22z3WI1oDNnx8SR9rD3fUeiMibaXi', 'ADMIN', NULL, '2026-02-15 16:33:41.725468'),
     (7, 'Agent TnD', 'Agent@tnd.dz', '$2b$10$I7meLngr/f/.2gbNg1iYSuAJE7T2jDjJKoTGfjv0T0.sisI8eJhSq', 'AGENT', NULL, '2026-02-16 16:36:05.274116'),
     (8, 'Client ooredoo', 'Client@ooredoo.dz', '$2b$10$qWqcuBBDohqdnkOSGPdpT./CIcvQ0TaeIV2e7b.sad6gZYPCit6FC', 'CLIENT', 7, '2026-02-16 16:36:51.993931');

     INSERT INTO public.tickets (id, title, description, product, category, department, priority, urgency, status, created_by, society_id, assigned_agent_id, created_at, updated_at) VALUES
     (2, 'test', 'hello', 'Fortinet', 'test', 'info', 'HIGH', 'Medium', 'OPEN', 5, 6, NULL, '2026-02-16 12:17:00.966489', '2026-02-16 12:17:00.966489'),
     (1, 'bdj', 'hebdhjb', 'Cisco', 'hjdbw', 'wdbhj', 'LOW', 'Low', 'IN_PROGRESS', 1, NULL, 1, '2026-02-14 22:06:37.333121', '2026-02-16 14:20:17.949584'),
     (3, 'Internet Not Working', 'My home fiber connection has been down since yesterday evening around 8 PM.', 'Cisco', 'Internet / Fiber', '/', 'HIGH', 'High', 'OPEN', 8, 7, NULL, '2026-02-16 16:41:56.030648', '2026-02-16 16:41:56.030648');

     INSERT INTO public.comments (id, ticket_id, user_id, content, created_at) VALUES
     (1, 2, 1, 'test', '2026-02-16 12:24:10.64875'),
     (2, 2, 1, 'try to log in', '2026-02-16 12:25:24.157223'),
     (3, 2, 5, 'thx', '2026-02-16 16:07:15.369399');


     SELECT pg_catalog.setval('public.societies_id_seq', 10, true);
     SELECT pg_catalog.setval('public.users_id_seq', 8, true);
     SELECT pg_catalog.setval('public.tickets_id_seq', 3, true);
     SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


     CREATE INDEX idx_users_society_id ON public.users(society_id);
     CREATE INDEX idx_tickets_created_by ON public.tickets(created_by);
     CREATE INDEX idx_tickets_assigned_agent ON public.tickets(assigned_agent_id);
     CREATE INDEX idx_tickets_society_id ON public.tickets(society_id);
     CREATE INDEX idx_comments_ticket_id ON public.comments(ticket_id);
     CREATE INDEX idx_attachments_ticket_id ON public.attachments(ticket_id);

