apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: production
  UPLOAD_DIR: "/app/uploads"
  DB_HOST: db-service
  DB_PORT: "5432"
  VITE_API_URL: "https://api-ticket-system.apps.green.tnd.linux"
  CORS_ORIGINS: "https://frontend-ticket-system.apps.green.tnd.linux"
