name: Trivy Test

on:
  workflow_dispatch:

jobs:
  test-trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Test Trivy on vulnerable image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: alpine:3.10
          severity: HIGH,CRITICAL
          exit-code: 1
